// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zjhuserinfo.proto

#ifndef PROTOBUF_zjhuserinfo_2eproto__INCLUDED
#define PROTOBUF_zjhuserinfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace zjhuserinfo {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_zjhuserinfo_2eproto();
void protobuf_AssignDesc_zjhuserinfo_2eproto();
void protobuf_ShutdownFile_zjhuserinfo_2eproto();

class Card;
class zjhDeskResultinfo;
class zjhDeskUserinfo;
class zjhDeskinfo;
class zjhMatchInfo;
class zjhSelfRoomInfo;
class zjhUserResultinfo;
class zjhUserinfo;

// ===================================================================

class zjhUserinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhUserinfo) */ {
 public:
  zjhUserinfo();
  virtual ~zjhUserinfo();

  zjhUserinfo(const zjhUserinfo& from);

  inline zjhUserinfo& operator=(const zjhUserinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhUserinfo& default_instance();

  void Swap(zjhUserinfo* other);

  // implements Message ----------------------------------------------

  inline zjhUserinfo* New() const { return New(NULL); }

  zjhUserinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhUserinfo& from);
  void MergeFrom(const zjhUserinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhUserinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // optional bytes uname = 2;
  void clear_uname();
  static const int kUnameFieldNumber = 2;
  const ::std::string& uname() const;
  void set_uname(const ::std::string& value);
  void set_uname(const char* value);
  void set_uname(const void* value, size_t size);
  ::std::string* mutable_uname();
  ::std::string* release_uname();
  void set_allocated_uname(::std::string* uname);

  // optional uint32 coinnum = 3;
  void clear_coinnum();
  static const int kCoinnumFieldNumber = 3;
  ::google::protobuf::uint32 coinnum() const;
  void set_coinnum(::google::protobuf::uint32 value);

  // optional uint32 integral = 4;
  void clear_integral();
  static const int kIntegralFieldNumber = 4;
  ::google::protobuf::uint32 integral() const;
  void set_integral(::google::protobuf::uint32 value);

  // optional uint32 ingotnum = 5;
  void clear_ingotnum();
  static const int kIngotnumFieldNumber = 5;
  ::google::protobuf::uint32 ingotnum() const;
  void set_ingotnum(::google::protobuf::uint32 value);

  // optional uint32 gender = 6;
  void clear_gender();
  static const int kGenderFieldNumber = 6;
  ::google::protobuf::uint32 gender() const;
  void set_gender(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhUserinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr uname_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 coinnum_;
  ::google::protobuf::uint32 integral_;
  ::google::protobuf::uint32 ingotnum_;
  ::google::protobuf::uint32 gender_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhUserinfo* default_instance_;
};
// -------------------------------------------------------------------

class Card : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.Card) */ {
 public:
  Card();
  virtual ~Card();

  Card(const Card& from);

  inline Card& operator=(const Card& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Card& default_instance();

  void Swap(Card* other);

  // implements Message ----------------------------------------------

  inline Card* New() const { return New(NULL); }

  Card* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Card& from);
  void MergeFrom(const Card& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Card* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::uint32 value() const;
  void set_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.Card)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static Card* default_instance_;
};
// -------------------------------------------------------------------

class zjhDeskUserinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhDeskUserinfo) */ {
 public:
  zjhDeskUserinfo();
  virtual ~zjhDeskUserinfo();

  zjhDeskUserinfo(const zjhDeskUserinfo& from);

  inline zjhDeskUserinfo& operator=(const zjhDeskUserinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhDeskUserinfo& default_instance();

  void Swap(zjhDeskUserinfo* other);

  // implements Message ----------------------------------------------

  inline zjhDeskUserinfo* New() const { return New(NULL); }

  zjhDeskUserinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhDeskUserinfo& from);
  void MergeFrom(const zjhDeskUserinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhDeskUserinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // optional bytes uname = 2;
  void clear_uname();
  static const int kUnameFieldNumber = 2;
  const ::std::string& uname() const;
  void set_uname(const ::std::string& value);
  void set_uname(const char* value);
  void set_uname(const void* value, size_t size);
  ::std::string* mutable_uname();
  ::std::string* release_uname();
  void set_allocated_uname(::std::string* uname);

  // optional uint32 coinnum = 3;
  void clear_coinnum();
  static const int kCoinnumFieldNumber = 3;
  ::google::protobuf::uint32 coinnum() const;
  void set_coinnum(::google::protobuf::uint32 value);

  // optional bytes headurl = 4;
  void clear_headurl();
  static const int kHeadurlFieldNumber = 4;
  const ::std::string& headurl() const;
  void set_headurl(const ::std::string& value);
  void set_headurl(const char* value);
  void set_headurl(const void* value, size_t size);
  ::std::string* mutable_headurl();
  ::std::string* release_headurl();
  void set_allocated_headurl(::std::string* headurl);

  // optional uint32 deskid = 5;
  void clear_deskid();
  static const int kDeskidFieldNumber = 5;
  ::google::protobuf::uint32 deskid() const;
  void set_deskid(::google::protobuf::uint32 value);

  // optional uint32 pos = 6;
  void clear_pos();
  static const int kPosFieldNumber = 6;
  ::google::protobuf::uint32 pos() const;
  void set_pos(::google::protobuf::uint32 value);

  // optional uint32 status = 7;
  void clear_status();
  static const int kStatusFieldNumber = 7;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // optional uint32 offline = 8;
  void clear_offline();
  static const int kOfflineFieldNumber = 8;
  ::google::protobuf::uint32 offline() const;
  void set_offline(::google::protobuf::uint32 value);

  // optional uint32 ifauto = 9;
  void clear_ifauto();
  static const int kIfautoFieldNumber = 9;
  ::google::protobuf::uint32 ifauto() const;
  void set_ifauto(::google::protobuf::uint32 value);

  // repeated .zjhuserinfo.Card poker = 10;
  int poker_size() const;
  void clear_poker();
  static const int kPokerFieldNumber = 10;
  const ::zjhuserinfo::Card& poker(int index) const;
  ::zjhuserinfo::Card* mutable_poker(int index);
  ::zjhuserinfo::Card* add_poker();
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >*
      mutable_poker();
  const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >&
      poker() const;

  // optional uint32 gender = 11;
  void clear_gender();
  static const int kGenderFieldNumber = 11;
  ::google::protobuf::uint32 gender() const;
  void set_gender(::google::protobuf::uint32 value);

  // optional int32 matchscore = 12;
  void clear_matchscore();
  static const int kMatchscoreFieldNumber = 12;
  ::google::protobuf::int32 matchscore() const;
  void set_matchscore(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhDeskUserinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr uname_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 coinnum_;
  ::google::protobuf::internal::ArenaStringPtr headurl_;
  ::google::protobuf::uint32 deskid_;
  ::google::protobuf::uint32 pos_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::uint32 offline_;
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card > poker_;
  ::google::protobuf::uint32 ifauto_;
  ::google::protobuf::uint32 gender_;
  ::google::protobuf::int32 matchscore_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhDeskUserinfo* default_instance_;
};
// -------------------------------------------------------------------

class zjhDeskinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhDeskinfo) */ {
 public:
  zjhDeskinfo();
  virtual ~zjhDeskinfo();

  zjhDeskinfo(const zjhDeskinfo& from);

  inline zjhDeskinfo& operator=(const zjhDeskinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhDeskinfo& default_instance();

  void Swap(zjhDeskinfo* other);

  // implements Message ----------------------------------------------

  inline zjhDeskinfo* New() const { return New(NULL); }

  zjhDeskinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhDeskinfo& from);
  void MergeFrom(const zjhDeskinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhDeskinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 deskid = 1;
  void clear_deskid();
  static const int kDeskidFieldNumber = 1;
  ::google::protobuf::uint32 deskid() const;
  void set_deskid(::google::protobuf::uint32 value);

  // optional uint32 status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // optional uint32 curpos = 3;
  void clear_curpos();
  static const int kCurposFieldNumber = 3;
  ::google::protobuf::uint32 curpos() const;
  void set_curpos(::google::protobuf::uint32 value);

  // optional uint32 sumTotal = 4;
  void clear_sumtotal();
  static const int kSumTotalFieldNumber = 4;
  ::google::protobuf::uint32 sumtotal() const;
  void set_sumtotal(::google::protobuf::uint32 value);

  // optional uint32 singleBet = 5;
  void clear_singlebet();
  static const int kSingleBetFieldNumber = 5;
  ::google::protobuf::uint32 singlebet() const;
  void set_singlebet(::google::protobuf::uint32 value);

  // repeated .zjhuserinfo.zjhDeskUserinfo userlist = 6;
  int userlist_size() const;
  void clear_userlist();
  static const int kUserlistFieldNumber = 6;
  const ::zjhuserinfo::zjhDeskUserinfo& userlist(int index) const;
  ::zjhuserinfo::zjhDeskUserinfo* mutable_userlist(int index);
  ::zjhuserinfo::zjhDeskUserinfo* add_userlist();
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhDeskUserinfo >*
      mutable_userlist();
  const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhDeskUserinfo >&
      userlist() const;

  // optional uint32 roundCount = 7;
  void clear_roundcount();
  static const int kRoundCountFieldNumber = 7;
  ::google::protobuf::uint32 roundcount() const;
  void set_roundcount(::google::protobuf::uint32 value);

  // optional uint32 matchid = 8;
  void clear_matchid();
  static const int kMatchidFieldNumber = 8;
  ::google::protobuf::uint32 matchid() const;
  void set_matchid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhDeskinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 deskid_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::uint32 curpos_;
  ::google::protobuf::uint32 sumtotal_;
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhDeskUserinfo > userlist_;
  ::google::protobuf::uint32 singlebet_;
  ::google::protobuf::uint32 roundcount_;
  ::google::protobuf::uint32 matchid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhDeskinfo* default_instance_;
};
// -------------------------------------------------------------------

class zjhDeskResultinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhDeskResultinfo) */ {
 public:
  zjhDeskResultinfo();
  virtual ~zjhDeskResultinfo();

  zjhDeskResultinfo(const zjhDeskResultinfo& from);

  inline zjhDeskResultinfo& operator=(const zjhDeskResultinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhDeskResultinfo& default_instance();

  void Swap(zjhDeskResultinfo* other);

  // implements Message ----------------------------------------------

  inline zjhDeskResultinfo* New() const { return New(NULL); }

  zjhDeskResultinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhDeskResultinfo& from);
  void MergeFrom(const zjhDeskResultinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhDeskResultinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 point = 1;
  void clear_point();
  static const int kPointFieldNumber = 1;
  ::google::protobuf::uint32 point() const;
  void set_point(::google::protobuf::uint32 value);

  // optional uint32 sumTotal = 2;
  void clear_sumtotal();
  static const int kSumTotalFieldNumber = 2;
  ::google::protobuf::uint32 sumtotal() const;
  void set_sumtotal(::google::protobuf::uint32 value);

  // optional uint32 singleBet = 3;
  void clear_singlebet();
  static const int kSingleBetFieldNumber = 3;
  ::google::protobuf::uint32 singlebet() const;
  void set_singlebet(::google::protobuf::uint32 value);

  // repeated .zjhuserinfo.zjhUserResultinfo userlist = 4;
  int userlist_size() const;
  void clear_userlist();
  static const int kUserlistFieldNumber = 4;
  const ::zjhuserinfo::zjhUserResultinfo& userlist(int index) const;
  ::zjhuserinfo::zjhUserResultinfo* mutable_userlist(int index);
  ::zjhuserinfo::zjhUserResultinfo* add_userlist();
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhUserResultinfo >*
      mutable_userlist();
  const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhUserResultinfo >&
      userlist() const;

  // optional int32 winpos = 5;
  void clear_winpos();
  static const int kWinposFieldNumber = 5;
  ::google::protobuf::int32 winpos() const;
  void set_winpos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhDeskResultinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 point_;
  ::google::protobuf::uint32 sumtotal_;
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhUserResultinfo > userlist_;
  ::google::protobuf::uint32 singlebet_;
  ::google::protobuf::int32 winpos_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhDeskResultinfo* default_instance_;
};
// -------------------------------------------------------------------

class zjhUserResultinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhUserResultinfo) */ {
 public:
  zjhUserResultinfo();
  virtual ~zjhUserResultinfo();

  zjhUserResultinfo(const zjhUserResultinfo& from);

  inline zjhUserResultinfo& operator=(const zjhUserResultinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhUserResultinfo& default_instance();

  void Swap(zjhUserResultinfo* other);

  // implements Message ----------------------------------------------

  inline zjhUserResultinfo* New() const { return New(NULL); }

  zjhUserResultinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhUserResultinfo& from);
  void MergeFrom(const zjhUserResultinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhUserResultinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // optional uint32 pos = 2;
  void clear_pos();
  static const int kPosFieldNumber = 2;
  ::google::protobuf::uint32 pos() const;
  void set_pos(::google::protobuf::uint32 value);

  // repeated .zjhuserinfo.Card usercard = 3;
  int usercard_size() const;
  void clear_usercard();
  static const int kUsercardFieldNumber = 3;
  const ::zjhuserinfo::Card& usercard(int index) const;
  ::zjhuserinfo::Card* mutable_usercard(int index);
  ::zjhuserinfo::Card* add_usercard();
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >*
      mutable_usercard();
  const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >&
      usercard() const;

  // optional int32 gamevalue = 4;
  void clear_gamevalue();
  static const int kGamevalueFieldNumber = 4;
  ::google::protobuf::int32 gamevalue() const;
  void set_gamevalue(::google::protobuf::int32 value);

  // optional uint32 rank = 5;
  void clear_rank();
  static const int kRankFieldNumber = 5;
  ::google::protobuf::uint32 rank() const;
  void set_rank(::google::protobuf::uint32 value);

  // optional int32 leftcount = 6;
  void clear_leftcount();
  static const int kLeftcountFieldNumber = 6;
  ::google::protobuf::int32 leftcount() const;
  void set_leftcount(::google::protobuf::int32 value);

  // optional uint32 leftvalue = 7;
  void clear_leftvalue();
  static const int kLeftvalueFieldNumber = 7;
  ::google::protobuf::uint32 leftvalue() const;
  void set_leftvalue(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhUserResultinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 pos_;
  ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card > usercard_;
  ::google::protobuf::int32 gamevalue_;
  ::google::protobuf::uint32 rank_;
  ::google::protobuf::int32 leftcount_;
  ::google::protobuf::uint32 leftvalue_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhUserResultinfo* default_instance_;
};
// -------------------------------------------------------------------

class zjhMatchInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhMatchInfo) */ {
 public:
  zjhMatchInfo();
  virtual ~zjhMatchInfo();

  zjhMatchInfo(const zjhMatchInfo& from);

  inline zjhMatchInfo& operator=(const zjhMatchInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhMatchInfo& default_instance();

  void Swap(zjhMatchInfo* other);

  // implements Message ----------------------------------------------

  inline zjhMatchInfo* New() const { return New(NULL); }

  zjhMatchInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhMatchInfo& from);
  void MergeFrom(const zjhMatchInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhMatchInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 matchid = 1;
  void clear_matchid();
  static const int kMatchidFieldNumber = 1;
  ::google::protobuf::uint32 matchid() const;
  void set_matchid(::google::protobuf::uint32 value);

  // optional uint32 trunindex = 2;
  void clear_trunindex();
  static const int kTrunindexFieldNumber = 2;
  ::google::protobuf::uint32 trunindex() const;
  void set_trunindex(::google::protobuf::uint32 value);

  // optional uint32 curnum = 3;
  void clear_curnum();
  static const int kCurnumFieldNumber = 3;
  ::google::protobuf::uint32 curnum() const;
  void set_curnum(::google::protobuf::uint32 value);

  // optional int32 gamevalue = 4;
  void clear_gamevalue();
  static const int kGamevalueFieldNumber = 4;
  ::google::protobuf::int32 gamevalue() const;
  void set_gamevalue(::google::protobuf::int32 value);

  // optional int32 ifmatch = 5;
  void clear_ifmatch();
  static const int kIfmatchFieldNumber = 5;
  ::google::protobuf::int32 ifmatch() const;
  void set_ifmatch(::google::protobuf::int32 value);

  // optional uint32 leftnum = 6;
  void clear_leftnum();
  static const int kLeftnumFieldNumber = 6;
  ::google::protobuf::uint32 leftnum() const;
  void set_leftnum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhMatchInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 matchid_;
  ::google::protobuf::uint32 trunindex_;
  ::google::protobuf::uint32 curnum_;
  ::google::protobuf::int32 gamevalue_;
  ::google::protobuf::int32 ifmatch_;
  ::google::protobuf::uint32 leftnum_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhMatchInfo* default_instance_;
};
// -------------------------------------------------------------------

class zjhSelfRoomInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjhuserinfo.zjhSelfRoomInfo) */ {
 public:
  zjhSelfRoomInfo();
  virtual ~zjhSelfRoomInfo();

  zjhSelfRoomInfo(const zjhSelfRoomInfo& from);

  inline zjhSelfRoomInfo& operator=(const zjhSelfRoomInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const zjhSelfRoomInfo& default_instance();

  void Swap(zjhSelfRoomInfo* other);

  // implements Message ----------------------------------------------

  inline zjhSelfRoomInfo* New() const { return New(NULL); }

  zjhSelfRoomInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const zjhSelfRoomInfo& from);
  void MergeFrom(const zjhSelfRoomInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(zjhSelfRoomInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::uint32 roomid() const;
  void set_roomid(::google::protobuf::uint32 value);

  // optional bytes roomcode = 2;
  void clear_roomcode();
  static const int kRoomcodeFieldNumber = 2;
  const ::std::string& roomcode() const;
  void set_roomcode(const ::std::string& value);
  void set_roomcode(const char* value);
  void set_roomcode(const void* value, size_t size);
  ::std::string* mutable_roomcode();
  ::std::string* release_roomcode();
  void set_allocated_roomcode(::std::string* roomcode);

  // optional uint32 endtime = 3;
  void clear_endtime();
  static const int kEndtimeFieldNumber = 3;
  ::google::protobuf::uint32 endtime() const;
  void set_endtime(::google::protobuf::uint32 value);

  // optional uint32 createuid = 4;
  void clear_createuid();
  static const int kCreateuidFieldNumber = 4;
  ::google::protobuf::uint32 createuid() const;
  void set_createuid(::google::protobuf::uint32 value);

  // optional uint32 basecoin = 5;
  void clear_basecoin();
  static const int kBasecoinFieldNumber = 5;
  ::google::protobuf::uint32 basecoin() const;
  void set_basecoin(::google::protobuf::uint32 value);

  // optional uint32 playcount = 6;
  void clear_playcount();
  static const int kPlaycountFieldNumber = 6;
  ::google::protobuf::uint32 playcount() const;
  void set_playcount(::google::protobuf::uint32 value);

  // optional int32 pos = 7;
  void clear_pos();
  static const int kPosFieldNumber = 7;
  ::google::protobuf::int32 pos() const;
  void set_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zjhuserinfo.zjhSelfRoomInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr roomcode_;
  ::google::protobuf::uint32 roomid_;
  ::google::protobuf::uint32 endtime_;
  ::google::protobuf::uint32 createuid_;
  ::google::protobuf::uint32 basecoin_;
  ::google::protobuf::uint32 playcount_;
  ::google::protobuf::int32 pos_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_zjhuserinfo_2eproto();
  friend void protobuf_AssignDesc_zjhuserinfo_2eproto();
  friend void protobuf_ShutdownFile_zjhuserinfo_2eproto();

  void InitAsDefaultInstance();
  static zjhSelfRoomInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// zjhUserinfo

// optional uint32 uid = 1;
inline void zjhUserinfo::clear_uid() {
  uid_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserinfo::uid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.uid)
  return uid_;
}
inline void zjhUserinfo::set_uid(::google::protobuf::uint32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.uid)
}

// optional bytes uname = 2;
inline void zjhUserinfo::clear_uname() {
  uname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& zjhUserinfo::uname() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.uname)
  return uname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhUserinfo::set_uname(const ::std::string& value) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.uname)
}
inline void zjhUserinfo::set_uname(const char* value) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjhuserinfo.zjhUserinfo.uname)
}
inline void zjhUserinfo::set_uname(const void* value, size_t size) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjhuserinfo.zjhUserinfo.uname)
}
inline ::std::string* zjhUserinfo::mutable_uname() {
  
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhUserinfo.uname)
  return uname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* zjhUserinfo::release_uname() {
  // @@protoc_insertion_point(field_release:zjhuserinfo.zjhUserinfo.uname)
  
  return uname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhUserinfo::set_allocated_uname(::std::string* uname) {
  if (uname != NULL) {
    
  } else {
    
  }
  uname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uname);
  // @@protoc_insertion_point(field_set_allocated:zjhuserinfo.zjhUserinfo.uname)
}

// optional uint32 coinnum = 3;
inline void zjhUserinfo::clear_coinnum() {
  coinnum_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserinfo::coinnum() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.coinnum)
  return coinnum_;
}
inline void zjhUserinfo::set_coinnum(::google::protobuf::uint32 value) {
  
  coinnum_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.coinnum)
}

// optional uint32 integral = 4;
inline void zjhUserinfo::clear_integral() {
  integral_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserinfo::integral() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.integral)
  return integral_;
}
inline void zjhUserinfo::set_integral(::google::protobuf::uint32 value) {
  
  integral_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.integral)
}

// optional uint32 ingotnum = 5;
inline void zjhUserinfo::clear_ingotnum() {
  ingotnum_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserinfo::ingotnum() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.ingotnum)
  return ingotnum_;
}
inline void zjhUserinfo::set_ingotnum(::google::protobuf::uint32 value) {
  
  ingotnum_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.ingotnum)
}

// optional uint32 gender = 6;
inline void zjhUserinfo::clear_gender() {
  gender_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserinfo::gender() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserinfo.gender)
  return gender_;
}
inline void zjhUserinfo::set_gender(::google::protobuf::uint32 value) {
  
  gender_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserinfo.gender)
}

// -------------------------------------------------------------------

// Card

// optional uint32 value = 1;
inline void Card::clear_value() {
  value_ = 0u;
}
inline ::google::protobuf::uint32 Card::value() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.Card.value)
  return value_;
}
inline void Card::set_value(::google::protobuf::uint32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.Card.value)
}

// -------------------------------------------------------------------

// zjhDeskUserinfo

// optional uint32 uid = 1;
inline void zjhDeskUserinfo::clear_uid() {
  uid_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::uid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.uid)
  return uid_;
}
inline void zjhDeskUserinfo::set_uid(::google::protobuf::uint32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.uid)
}

// optional bytes uname = 2;
inline void zjhDeskUserinfo::clear_uname() {
  uname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& zjhDeskUserinfo::uname() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.uname)
  return uname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhDeskUserinfo::set_uname(const ::std::string& value) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.uname)
}
inline void zjhDeskUserinfo::set_uname(const char* value) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjhuserinfo.zjhDeskUserinfo.uname)
}
inline void zjhDeskUserinfo::set_uname(const void* value, size_t size) {
  
  uname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjhuserinfo.zjhDeskUserinfo.uname)
}
inline ::std::string* zjhDeskUserinfo::mutable_uname() {
  
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhDeskUserinfo.uname)
  return uname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* zjhDeskUserinfo::release_uname() {
  // @@protoc_insertion_point(field_release:zjhuserinfo.zjhDeskUserinfo.uname)
  
  return uname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhDeskUserinfo::set_allocated_uname(::std::string* uname) {
  if (uname != NULL) {
    
  } else {
    
  }
  uname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uname);
  // @@protoc_insertion_point(field_set_allocated:zjhuserinfo.zjhDeskUserinfo.uname)
}

// optional uint32 coinnum = 3;
inline void zjhDeskUserinfo::clear_coinnum() {
  coinnum_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::coinnum() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.coinnum)
  return coinnum_;
}
inline void zjhDeskUserinfo::set_coinnum(::google::protobuf::uint32 value) {
  
  coinnum_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.coinnum)
}

// optional bytes headurl = 4;
inline void zjhDeskUserinfo::clear_headurl() {
  headurl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& zjhDeskUserinfo::headurl() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.headurl)
  return headurl_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhDeskUserinfo::set_headurl(const ::std::string& value) {
  
  headurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.headurl)
}
inline void zjhDeskUserinfo::set_headurl(const char* value) {
  
  headurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjhuserinfo.zjhDeskUserinfo.headurl)
}
inline void zjhDeskUserinfo::set_headurl(const void* value, size_t size) {
  
  headurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjhuserinfo.zjhDeskUserinfo.headurl)
}
inline ::std::string* zjhDeskUserinfo::mutable_headurl() {
  
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhDeskUserinfo.headurl)
  return headurl_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* zjhDeskUserinfo::release_headurl() {
  // @@protoc_insertion_point(field_release:zjhuserinfo.zjhDeskUserinfo.headurl)
  
  return headurl_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhDeskUserinfo::set_allocated_headurl(::std::string* headurl) {
  if (headurl != NULL) {
    
  } else {
    
  }
  headurl_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), headurl);
  // @@protoc_insertion_point(field_set_allocated:zjhuserinfo.zjhDeskUserinfo.headurl)
}

// optional uint32 deskid = 5;
inline void zjhDeskUserinfo::clear_deskid() {
  deskid_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::deskid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.deskid)
  return deskid_;
}
inline void zjhDeskUserinfo::set_deskid(::google::protobuf::uint32 value) {
  
  deskid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.deskid)
}

// optional uint32 pos = 6;
inline void zjhDeskUserinfo::clear_pos() {
  pos_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::pos() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.pos)
  return pos_;
}
inline void zjhDeskUserinfo::set_pos(::google::protobuf::uint32 value) {
  
  pos_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.pos)
}

// optional uint32 status = 7;
inline void zjhDeskUserinfo::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::status() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.status)
  return status_;
}
inline void zjhDeskUserinfo::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.status)
}

// optional uint32 offline = 8;
inline void zjhDeskUserinfo::clear_offline() {
  offline_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::offline() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.offline)
  return offline_;
}
inline void zjhDeskUserinfo::set_offline(::google::protobuf::uint32 value) {
  
  offline_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.offline)
}

// optional uint32 ifauto = 9;
inline void zjhDeskUserinfo::clear_ifauto() {
  ifauto_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::ifauto() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.ifauto)
  return ifauto_;
}
inline void zjhDeskUserinfo::set_ifauto(::google::protobuf::uint32 value) {
  
  ifauto_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.ifauto)
}

// repeated .zjhuserinfo.Card poker = 10;
inline int zjhDeskUserinfo::poker_size() const {
  return poker_.size();
}
inline void zjhDeskUserinfo::clear_poker() {
  poker_.Clear();
}
inline const ::zjhuserinfo::Card& zjhDeskUserinfo::poker(int index) const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.poker)
  return poker_.Get(index);
}
inline ::zjhuserinfo::Card* zjhDeskUserinfo::mutable_poker(int index) {
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhDeskUserinfo.poker)
  return poker_.Mutable(index);
}
inline ::zjhuserinfo::Card* zjhDeskUserinfo::add_poker() {
  // @@protoc_insertion_point(field_add:zjhuserinfo.zjhDeskUserinfo.poker)
  return poker_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >*
zjhDeskUserinfo::mutable_poker() {
  // @@protoc_insertion_point(field_mutable_list:zjhuserinfo.zjhDeskUserinfo.poker)
  return &poker_;
}
inline const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >&
zjhDeskUserinfo::poker() const {
  // @@protoc_insertion_point(field_list:zjhuserinfo.zjhDeskUserinfo.poker)
  return poker_;
}

// optional uint32 gender = 11;
inline void zjhDeskUserinfo::clear_gender() {
  gender_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskUserinfo::gender() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.gender)
  return gender_;
}
inline void zjhDeskUserinfo::set_gender(::google::protobuf::uint32 value) {
  
  gender_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.gender)
}

// optional int32 matchscore = 12;
inline void zjhDeskUserinfo::clear_matchscore() {
  matchscore_ = 0;
}
inline ::google::protobuf::int32 zjhDeskUserinfo::matchscore() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskUserinfo.matchscore)
  return matchscore_;
}
inline void zjhDeskUserinfo::set_matchscore(::google::protobuf::int32 value) {
  
  matchscore_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskUserinfo.matchscore)
}

// -------------------------------------------------------------------

// zjhDeskinfo

// optional uint32 deskid = 1;
inline void zjhDeskinfo::clear_deskid() {
  deskid_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::deskid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.deskid)
  return deskid_;
}
inline void zjhDeskinfo::set_deskid(::google::protobuf::uint32 value) {
  
  deskid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.deskid)
}

// optional uint32 status = 2;
inline void zjhDeskinfo::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::status() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.status)
  return status_;
}
inline void zjhDeskinfo::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.status)
}

// optional uint32 curpos = 3;
inline void zjhDeskinfo::clear_curpos() {
  curpos_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::curpos() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.curpos)
  return curpos_;
}
inline void zjhDeskinfo::set_curpos(::google::protobuf::uint32 value) {
  
  curpos_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.curpos)
}

// optional uint32 sumTotal = 4;
inline void zjhDeskinfo::clear_sumtotal() {
  sumtotal_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::sumtotal() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.sumTotal)
  return sumtotal_;
}
inline void zjhDeskinfo::set_sumtotal(::google::protobuf::uint32 value) {
  
  sumtotal_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.sumTotal)
}

// optional uint32 singleBet = 5;
inline void zjhDeskinfo::clear_singlebet() {
  singlebet_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::singlebet() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.singleBet)
  return singlebet_;
}
inline void zjhDeskinfo::set_singlebet(::google::protobuf::uint32 value) {
  
  singlebet_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.singleBet)
}

// repeated .zjhuserinfo.zjhDeskUserinfo userlist = 6;
inline int zjhDeskinfo::userlist_size() const {
  return userlist_.size();
}
inline void zjhDeskinfo::clear_userlist() {
  userlist_.Clear();
}
inline const ::zjhuserinfo::zjhDeskUserinfo& zjhDeskinfo::userlist(int index) const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.userlist)
  return userlist_.Get(index);
}
inline ::zjhuserinfo::zjhDeskUserinfo* zjhDeskinfo::mutable_userlist(int index) {
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhDeskinfo.userlist)
  return userlist_.Mutable(index);
}
inline ::zjhuserinfo::zjhDeskUserinfo* zjhDeskinfo::add_userlist() {
  // @@protoc_insertion_point(field_add:zjhuserinfo.zjhDeskinfo.userlist)
  return userlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhDeskUserinfo >*
zjhDeskinfo::mutable_userlist() {
  // @@protoc_insertion_point(field_mutable_list:zjhuserinfo.zjhDeskinfo.userlist)
  return &userlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhDeskUserinfo >&
zjhDeskinfo::userlist() const {
  // @@protoc_insertion_point(field_list:zjhuserinfo.zjhDeskinfo.userlist)
  return userlist_;
}

// optional uint32 roundCount = 7;
inline void zjhDeskinfo::clear_roundcount() {
  roundcount_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::roundcount() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.roundCount)
  return roundcount_;
}
inline void zjhDeskinfo::set_roundcount(::google::protobuf::uint32 value) {
  
  roundcount_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.roundCount)
}

// optional uint32 matchid = 8;
inline void zjhDeskinfo::clear_matchid() {
  matchid_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskinfo::matchid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskinfo.matchid)
  return matchid_;
}
inline void zjhDeskinfo::set_matchid(::google::protobuf::uint32 value) {
  
  matchid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskinfo.matchid)
}

// -------------------------------------------------------------------

// zjhDeskResultinfo

// optional uint32 point = 1;
inline void zjhDeskResultinfo::clear_point() {
  point_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskResultinfo::point() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskResultinfo.point)
  return point_;
}
inline void zjhDeskResultinfo::set_point(::google::protobuf::uint32 value) {
  
  point_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskResultinfo.point)
}

// optional uint32 sumTotal = 2;
inline void zjhDeskResultinfo::clear_sumtotal() {
  sumtotal_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskResultinfo::sumtotal() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskResultinfo.sumTotal)
  return sumtotal_;
}
inline void zjhDeskResultinfo::set_sumtotal(::google::protobuf::uint32 value) {
  
  sumtotal_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskResultinfo.sumTotal)
}

// optional uint32 singleBet = 3;
inline void zjhDeskResultinfo::clear_singlebet() {
  singlebet_ = 0u;
}
inline ::google::protobuf::uint32 zjhDeskResultinfo::singlebet() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskResultinfo.singleBet)
  return singlebet_;
}
inline void zjhDeskResultinfo::set_singlebet(::google::protobuf::uint32 value) {
  
  singlebet_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskResultinfo.singleBet)
}

// repeated .zjhuserinfo.zjhUserResultinfo userlist = 4;
inline int zjhDeskResultinfo::userlist_size() const {
  return userlist_.size();
}
inline void zjhDeskResultinfo::clear_userlist() {
  userlist_.Clear();
}
inline const ::zjhuserinfo::zjhUserResultinfo& zjhDeskResultinfo::userlist(int index) const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskResultinfo.userlist)
  return userlist_.Get(index);
}
inline ::zjhuserinfo::zjhUserResultinfo* zjhDeskResultinfo::mutable_userlist(int index) {
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhDeskResultinfo.userlist)
  return userlist_.Mutable(index);
}
inline ::zjhuserinfo::zjhUserResultinfo* zjhDeskResultinfo::add_userlist() {
  // @@protoc_insertion_point(field_add:zjhuserinfo.zjhDeskResultinfo.userlist)
  return userlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhUserResultinfo >*
zjhDeskResultinfo::mutable_userlist() {
  // @@protoc_insertion_point(field_mutable_list:zjhuserinfo.zjhDeskResultinfo.userlist)
  return &userlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::zjhUserResultinfo >&
zjhDeskResultinfo::userlist() const {
  // @@protoc_insertion_point(field_list:zjhuserinfo.zjhDeskResultinfo.userlist)
  return userlist_;
}

// optional int32 winpos = 5;
inline void zjhDeskResultinfo::clear_winpos() {
  winpos_ = 0;
}
inline ::google::protobuf::int32 zjhDeskResultinfo::winpos() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhDeskResultinfo.winpos)
  return winpos_;
}
inline void zjhDeskResultinfo::set_winpos(::google::protobuf::int32 value) {
  
  winpos_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhDeskResultinfo.winpos)
}

// -------------------------------------------------------------------

// zjhUserResultinfo

// optional uint32 uid = 1;
inline void zjhUserResultinfo::clear_uid() {
  uid_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserResultinfo::uid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.uid)
  return uid_;
}
inline void zjhUserResultinfo::set_uid(::google::protobuf::uint32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.uid)
}

// optional uint32 pos = 2;
inline void zjhUserResultinfo::clear_pos() {
  pos_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserResultinfo::pos() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.pos)
  return pos_;
}
inline void zjhUserResultinfo::set_pos(::google::protobuf::uint32 value) {
  
  pos_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.pos)
}

// repeated .zjhuserinfo.Card usercard = 3;
inline int zjhUserResultinfo::usercard_size() const {
  return usercard_.size();
}
inline void zjhUserResultinfo::clear_usercard() {
  usercard_.Clear();
}
inline const ::zjhuserinfo::Card& zjhUserResultinfo::usercard(int index) const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.usercard)
  return usercard_.Get(index);
}
inline ::zjhuserinfo::Card* zjhUserResultinfo::mutable_usercard(int index) {
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhUserResultinfo.usercard)
  return usercard_.Mutable(index);
}
inline ::zjhuserinfo::Card* zjhUserResultinfo::add_usercard() {
  // @@protoc_insertion_point(field_add:zjhuserinfo.zjhUserResultinfo.usercard)
  return usercard_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >*
zjhUserResultinfo::mutable_usercard() {
  // @@protoc_insertion_point(field_mutable_list:zjhuserinfo.zjhUserResultinfo.usercard)
  return &usercard_;
}
inline const ::google::protobuf::RepeatedPtrField< ::zjhuserinfo::Card >&
zjhUserResultinfo::usercard() const {
  // @@protoc_insertion_point(field_list:zjhuserinfo.zjhUserResultinfo.usercard)
  return usercard_;
}

// optional int32 gamevalue = 4;
inline void zjhUserResultinfo::clear_gamevalue() {
  gamevalue_ = 0;
}
inline ::google::protobuf::int32 zjhUserResultinfo::gamevalue() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.gamevalue)
  return gamevalue_;
}
inline void zjhUserResultinfo::set_gamevalue(::google::protobuf::int32 value) {
  
  gamevalue_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.gamevalue)
}

// optional uint32 rank = 5;
inline void zjhUserResultinfo::clear_rank() {
  rank_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserResultinfo::rank() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.rank)
  return rank_;
}
inline void zjhUserResultinfo::set_rank(::google::protobuf::uint32 value) {
  
  rank_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.rank)
}

// optional int32 leftcount = 6;
inline void zjhUserResultinfo::clear_leftcount() {
  leftcount_ = 0;
}
inline ::google::protobuf::int32 zjhUserResultinfo::leftcount() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.leftcount)
  return leftcount_;
}
inline void zjhUserResultinfo::set_leftcount(::google::protobuf::int32 value) {
  
  leftcount_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.leftcount)
}

// optional uint32 leftvalue = 7;
inline void zjhUserResultinfo::clear_leftvalue() {
  leftvalue_ = 0u;
}
inline ::google::protobuf::uint32 zjhUserResultinfo::leftvalue() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhUserResultinfo.leftvalue)
  return leftvalue_;
}
inline void zjhUserResultinfo::set_leftvalue(::google::protobuf::uint32 value) {
  
  leftvalue_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhUserResultinfo.leftvalue)
}

// -------------------------------------------------------------------

// zjhMatchInfo

// optional uint32 matchid = 1;
inline void zjhMatchInfo::clear_matchid() {
  matchid_ = 0u;
}
inline ::google::protobuf::uint32 zjhMatchInfo::matchid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.matchid)
  return matchid_;
}
inline void zjhMatchInfo::set_matchid(::google::protobuf::uint32 value) {
  
  matchid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.matchid)
}

// optional uint32 trunindex = 2;
inline void zjhMatchInfo::clear_trunindex() {
  trunindex_ = 0u;
}
inline ::google::protobuf::uint32 zjhMatchInfo::trunindex() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.trunindex)
  return trunindex_;
}
inline void zjhMatchInfo::set_trunindex(::google::protobuf::uint32 value) {
  
  trunindex_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.trunindex)
}

// optional uint32 curnum = 3;
inline void zjhMatchInfo::clear_curnum() {
  curnum_ = 0u;
}
inline ::google::protobuf::uint32 zjhMatchInfo::curnum() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.curnum)
  return curnum_;
}
inline void zjhMatchInfo::set_curnum(::google::protobuf::uint32 value) {
  
  curnum_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.curnum)
}

// optional int32 gamevalue = 4;
inline void zjhMatchInfo::clear_gamevalue() {
  gamevalue_ = 0;
}
inline ::google::protobuf::int32 zjhMatchInfo::gamevalue() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.gamevalue)
  return gamevalue_;
}
inline void zjhMatchInfo::set_gamevalue(::google::protobuf::int32 value) {
  
  gamevalue_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.gamevalue)
}

// optional int32 ifmatch = 5;
inline void zjhMatchInfo::clear_ifmatch() {
  ifmatch_ = 0;
}
inline ::google::protobuf::int32 zjhMatchInfo::ifmatch() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.ifmatch)
  return ifmatch_;
}
inline void zjhMatchInfo::set_ifmatch(::google::protobuf::int32 value) {
  
  ifmatch_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.ifmatch)
}

// optional uint32 leftnum = 6;
inline void zjhMatchInfo::clear_leftnum() {
  leftnum_ = 0u;
}
inline ::google::protobuf::uint32 zjhMatchInfo::leftnum() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhMatchInfo.leftnum)
  return leftnum_;
}
inline void zjhMatchInfo::set_leftnum(::google::protobuf::uint32 value) {
  
  leftnum_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhMatchInfo.leftnum)
}

// -------------------------------------------------------------------

// zjhSelfRoomInfo

// optional uint32 roomid = 1;
inline void zjhSelfRoomInfo::clear_roomid() {
  roomid_ = 0u;
}
inline ::google::protobuf::uint32 zjhSelfRoomInfo::roomid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.roomid)
  return roomid_;
}
inline void zjhSelfRoomInfo::set_roomid(::google::protobuf::uint32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.roomid)
}

// optional bytes roomcode = 2;
inline void zjhSelfRoomInfo::clear_roomcode() {
  roomcode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& zjhSelfRoomInfo::roomcode() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.roomcode)
  return roomcode_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhSelfRoomInfo::set_roomcode(const ::std::string& value) {
  
  roomcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.roomcode)
}
inline void zjhSelfRoomInfo::set_roomcode(const char* value) {
  
  roomcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjhuserinfo.zjhSelfRoomInfo.roomcode)
}
inline void zjhSelfRoomInfo::set_roomcode(const void* value, size_t size) {
  
  roomcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjhuserinfo.zjhSelfRoomInfo.roomcode)
}
inline ::std::string* zjhSelfRoomInfo::mutable_roomcode() {
  
  // @@protoc_insertion_point(field_mutable:zjhuserinfo.zjhSelfRoomInfo.roomcode)
  return roomcode_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* zjhSelfRoomInfo::release_roomcode() {
  // @@protoc_insertion_point(field_release:zjhuserinfo.zjhSelfRoomInfo.roomcode)
  
  return roomcode_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void zjhSelfRoomInfo::set_allocated_roomcode(::std::string* roomcode) {
  if (roomcode != NULL) {
    
  } else {
    
  }
  roomcode_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), roomcode);
  // @@protoc_insertion_point(field_set_allocated:zjhuserinfo.zjhSelfRoomInfo.roomcode)
}

// optional uint32 endtime = 3;
inline void zjhSelfRoomInfo::clear_endtime() {
  endtime_ = 0u;
}
inline ::google::protobuf::uint32 zjhSelfRoomInfo::endtime() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.endtime)
  return endtime_;
}
inline void zjhSelfRoomInfo::set_endtime(::google::protobuf::uint32 value) {
  
  endtime_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.endtime)
}

// optional uint32 createuid = 4;
inline void zjhSelfRoomInfo::clear_createuid() {
  createuid_ = 0u;
}
inline ::google::protobuf::uint32 zjhSelfRoomInfo::createuid() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.createuid)
  return createuid_;
}
inline void zjhSelfRoomInfo::set_createuid(::google::protobuf::uint32 value) {
  
  createuid_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.createuid)
}

// optional uint32 basecoin = 5;
inline void zjhSelfRoomInfo::clear_basecoin() {
  basecoin_ = 0u;
}
inline ::google::protobuf::uint32 zjhSelfRoomInfo::basecoin() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.basecoin)
  return basecoin_;
}
inline void zjhSelfRoomInfo::set_basecoin(::google::protobuf::uint32 value) {
  
  basecoin_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.basecoin)
}

// optional uint32 playcount = 6;
inline void zjhSelfRoomInfo::clear_playcount() {
  playcount_ = 0u;
}
inline ::google::protobuf::uint32 zjhSelfRoomInfo::playcount() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.playcount)
  return playcount_;
}
inline void zjhSelfRoomInfo::set_playcount(::google::protobuf::uint32 value) {
  
  playcount_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.playcount)
}

// optional int32 pos = 7;
inline void zjhSelfRoomInfo::clear_pos() {
  pos_ = 0;
}
inline ::google::protobuf::int32 zjhSelfRoomInfo::pos() const {
  // @@protoc_insertion_point(field_get:zjhuserinfo.zjhSelfRoomInfo.pos)
  return pos_;
}
inline void zjhSelfRoomInfo::set_pos(::google::protobuf::int32 value) {
  
  pos_ = value;
  // @@protoc_insertion_point(field_set:zjhuserinfo.zjhSelfRoomInfo.pos)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zjhuserinfo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zjhuserinfo_2eproto__INCLUDED
